# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=100)),
                ('time_way', models.CharField(max_length=100)),
            ],
        ),
    ]
