# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=100)),
                ('time_way', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
                ('positionName', models.CharField(max_length=50, null=True)),
                ('companyFullName', models.CharField(max_length=100, null=True)),
                ('companySize', models.CharField(max_length=20, null=True)),
                ('createTime', models.CharField(max_length=30, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('education', models.CharField(max_length=20, null=True)),
                ('industryField', models.CharField(max_length=50, null=True)),
                ('salary', models.CharField(max_length=20, null=True)),
                ('workYear', models.CharField(max_length=10, null=True)),
                ('financeStage', models.CharField(max_length=20, null=True)),
                ('jobNature', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
