# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('positionName', models.CharField(max_length=50)),
                ('companyFullName', models.CharField(max_length=100)),
                ('companySize', models.CharField(max_length=20)),
                ('createTime', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=20)),
                ('industryField', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('workYear', models.CharField(max_length=10)),
                ('financeStage', models.CharField(max_length=20)),
                ('jobNature', models.CharField(max_length=10)),
            ],
        ),
    ]
