# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagou', '0002_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='companyFullName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='companySize',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='createTime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='education',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='financeStage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='industryField',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='jobNature',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='positionName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='workYear',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
